Update workflow to generate html from OpenAPI spec (#4)
Co-authored-by: Hans Hsieh <hans@example.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,8 +2,6 @@
 
 name: CI
 
-# Controls when the action will run. Triggers the workflow on push or pull request
-# events but only for the master branch
 on:
   push:
     branches: [ master ]
@@ -21,13 +19,37 @@ jobs:
     steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2
+      with:
+        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
+        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
 
-    # Runs a single command using the runners shell
-    - name: Run a one-line script
-      run: echo Hello, world!
-
-    # Runs a set of commands using the runners shell
-    - name: Run a multi-line script
+    - name: Install node
+      uses: actions/setup-node@v2-beta
+      with:
+        node-version: '12'
+    
+    - name: Install OpenAPI generator CLI
       run: |
-        echo Add other actions to build,
-        echo test, and deploy your project.
+        sudo npm install @openapitools/openapi-generator-cli -g
+
+    - name: Convert API spec to HTML
+      run: |
+        openapi-generator generate -g html2 -i ./api.yaml -o "/tmp/output"
+
+    - name: Update gh-pages branch
+      if: ${{ github.event_name == 'push' }}
+      run: |
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git checkout gh-pages
+        rm -rf ./*
+        mv /tmp/output/* ./
+        git add .
+        git commit -m "Update doc" || true
+
+    - name: Push doc to git page
+      if: ${{ github.event_name == 'push' }}
+      uses: ad-m/github-push-action@master
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        branch: gh-pages
